#!/bin/bash
set -euo pipefail

MARKER_FILE="/var/lib/halos/gnss-marine-configured"
GPSD_DEFAULTS="/etc/default/gpsd"

FACTORY_BAUD=9600
TARGET_BAUD=115200
TARGET_RATE=100      # ms = 10 Hz
TARGET_MODEL=5       # Sea
DEFAULT_PROTVER=18
UBXTOOL_WAIT=4       # seconds

get_uart_devices() {
    if [ ! -f "$GPSD_DEFAULTS" ]; then
        return
    fi
    local devices
    # gpsd defaults file is generated by our build system (root-owned, simple key=value)
    # shellcheck source=/dev/null
    devices=$(. "$GPSD_DEFAULTS" && echo "${DEVICES:-}")
    for dev in $devices; do
        case "$dev" in
            /dev/ttyAMA*) echo "$dev" ;;
        esac
    done
}

probe_receiver() {
    local device="$1" baud="$2" output
    output=$(ubxtool -f "$device" -s "$baud" -w "$UBXTOOL_WAIT" -p MON-VER 2>/dev/null)
    # ubxtool exits 0 even with no response; validate actual UBX output
    echo "$output" | grep -q "MON-VER" || return 1
    echo "$output"
}

parse_protver() {
    local ver
    ver=$(echo "$1" | grep -oP 'PROTVER=\K[0-9]+' | head -1)
    echo "${ver:-$DEFAULT_PROTVER}"
}

run_ubxtool() {
    local device="$1" baud="$2" protver="$3"
    shift 3
    ubxtool -f "$device" -s "$baud" -P "$protver" -w "$UBXTOOL_WAIT" "$@" 2>/dev/null
}

configure_device() {
    local device="$1"
    echo "Configuring $device..."

    # Probe: try target baud first (already configured?), then factory
    local mon_ver="" current_baud=""
    for baud in "$TARGET_BAUD" "$FACTORY_BAUD"; do
        if mon_ver=$(probe_receiver "$device" "$baud"); then
            current_baud="$baud"
            break
        fi
    done

    if [ -z "$current_baud" ]; then
        echo "ERROR: No response from $device — skipping"
        return 1
    fi

    echo "Receiver responded at ${current_baud} bps"

    local protver
    protver=$(parse_protver "$mon_ver")
    echo "Protocol version: $protver"

    echo "Setting 10 Hz update rate..."
    run_ubxtool "$device" "$current_baud" "$protver" -p "CFG-RATE,$TARGET_RATE" \
        || { echo "ERROR: RATE failed"; return 1; }

    echo "Setting Sea dynamic model..."
    run_ubxtool "$device" "$current_baud" "$protver" -p "MODEL,$TARGET_MODEL" \
        || { echo "ERROR: MODEL failed"; return 1; }

    if [ "$current_baud" -ne "$TARGET_BAUD" ]; then
        echo "Changing baud rate to $TARGET_BAUD..."
        run_ubxtool "$device" "$current_baud" "$protver" -S "$TARGET_BAUD" \
            || { echo "ERROR: baud change failed"; return 1; }
        current_baud="$TARGET_BAUD"
        sleep 1
    fi

    echo "Saving to flash..."
    run_ubxtool "$device" "$current_baud" "$protver" -p SAVE \
        || { echo "ERROR: SAVE failed"; return 1; }

    echo "Successfully configured $device"
}

# --- Main ---

uart_devices=$(get_uart_devices)

if [ -z "$uart_devices" ]; then
    echo "No UART GNSS devices found — nothing to configure"
    mkdir -p "$(dirname "$MARKER_FILE")"
    touch "$MARKER_FILE"
    exit 0
fi

all_ok=true
for device in $uart_devices; do
    configure_device "$device" || all_ok=false
done

if [ "$all_ok" = true ]; then
    mkdir -p "$(dirname "$MARKER_FILE")"
    touch "$MARKER_FILE"
    echo "All GNSS receivers configured successfully"
else
    echo "WARNING: Some receivers failed — will retry on next boot"
    exit 1
fi
