#!/bin/bash -e

# Enable UART0 in boot config for MAX-M8Q GNSS HAT
cat files/config.txt.part >>"${ROOTFS_DIR}/boot/firmware/config.txt"

# Add HALPI2 GNSS device to gpsd config (overrides default from stage-halos-marine).
# u-blox receivers are configured to 115200 bps.
cat > "${ROOTFS_DIR}/etc/default/gpsd" << 'EOF'
# Generated by stage-halpi2-marine
DEVICES="/dev/ttyAMA0"
GPSD_OPTIONS="-n -s 115200"
USBAUTO=true
EOF
