#!/bin/bash -e

# Collect devices from drop-in directory (created by 00-setup-gnss-hat if present)
DEVICES=""
DEVICES_DIR="${ROOTFS_DIR}/etc/halos/gpsd-devices.d"
if [ -d "${DEVICES_DIR}" ]; then
    for f in "${DEVICES_DIR}"/*; do
        [ -f "$f" ] || continue
        while IFS= read -r device || [ -n "$device" ]; do
            [[ -z "$device" || "$device" =~ ^# ]] && continue
            DEVICES="${DEVICES} ${device}"
        done < "$f"
    done
fi
DEVICES="${DEVICES# }"  # Trim leading space

# Generate gpsd configuration
cat > "${ROOTFS_DIR}/etc/default/gpsd" << EOF
# Generated by stage-halos-marine
DEVICES="${DEVICES}"
GPSD_OPTIONS="-n"
USBAUTO=true
EOF
