#!/bin/bash -e

# Generate default gpsd configuration.
# HALPI2 variants override this in stage-halpi2-marine to add /dev/ttyAMA0.

cat > "${ROOTFS_DIR}/etc/default/gpsd" << 'EOF'
# Generated by stage-halos-marine
DEVICES=""
GPSD_OPTIONS="-n"
USBAUTO=true
EOF
